import type { ReactNode } from 'react';
import { ReportBrandMark } from './ReportBrandMark';
import { REPORT_FONT_DISPLAY, REPORT_TEXT, REPORT_TYPE } from './tokens';

export type ReportCoverProps = {
  title: string;
  subtitle?: string;
  preparedForLabel?: string;
  generatedByLabel?: string;
  dateLabel: string;
  /** Official logo on cover (bundled asset unless `logoSrc` set). */
  showBrandMark?: boolean;
  logoSrc?: string;
  /** Optional model-specific badge row */
  children?: ReactNode;
};

/**
 * First page — brand mark, then centered title block. Same structure for all four reports.
 */
export function ReportCover({
  title,
  subtitle,
  preparedForLabel = 'Prepared for: Client simulation',
  generatedByLabel = 'Generated by: Capital Bridge',
  dateLabel,
  showBrandMark = true,
  logoSrc,
  children,
}: ReportCoverProps) {
  return (
    <div
      style={{
        padding: '2em 0',
        minHeight: '80vh',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        textAlign: 'center',
      }}
    >
      {showBrandMark ? <ReportBrandMark logoSrc={logoSrc} /> : null}
      <h1
        style={{
          fontFamily: REPORT_FONT_DISPLAY,
          ...REPORT_TYPE.coverTitle,
          color: REPORT_TEXT,
          margin: '0 0 0.25em',
        }}
      >
        {title}
      </h1>
      {subtitle ? (
        <p
          style={{
            fontFamily: REPORT_FONT_DISPLAY,
            ...REPORT_TYPE.coverSubtitle,
            color: REPORT_TEXT,
            margin: '0 0 2em',
          }}
        >
          {subtitle}
        </p>
      ) : null}
      <p style={{ fontSize: '11pt', color: REPORT_TEXT, margin: '0.25em 0' }}>{preparedForLabel}</p>
      <p style={{ fontSize: '11pt', color: REPORT_TEXT, margin: '0.25em 0' }}>{generatedByLabel}</p>
      <p style={{ fontSize: '11pt', color: REPORT_TEXT, margin: '1em 0 0' }}>Date: {dateLabel}</p>
      {children}
    </div>
  );
}
