/**
 * AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
 * Source: /Lion Verdict dynamic copy.txt
 * Generator: scripts/sync-lion-copy.mjs
 */

export type Tier = 'STRONG' | 'STABLE' | 'FRAGILE' | 'AT_RISK' | 'NOT_SUSTAINABLE';

export type Line = {
  text: string;
  weight: number;
};

export const LION_COPY: Record<Tier, { headlines: Line[]; guidance: Line[] }> = {
  STRONG: {
    headlines: [
      { text: "The lion stands beyond pressure. Nothing reaches the core. The base remains untouched.", weight: 3 },
      { text: "The lion operates in excess. More than enough is available. Demand is easily absorbed.", weight: 3 },
      { text: "The lion is untouched at the core. No draw is required. Strength remains intact.", weight: 3 },
      { text: "The lion rests above all strain. The system carries itself. Effort is not needed.", weight: 3 },
      { text: "The lion stands insulated. Conditions do not affect outcomes. Stability is independent.", weight: 3 },
      { text: "The lion holds far above requirement. Surplus is consistent. There is always extra.", weight: 3 },
      { text: "The lion remains unaffected. Pressure stays outside. The core is preserved.", weight: 3 },
      { text: "The lion operates with deep reserve. Capacity exceeds all needs. Nothing is stretched.", weight: 3 },
      { text: "The lion stands complete. Nothing needs adjustment. The structure is overbuilt.", weight: 3 },
      { text: "The lion exists beyond risk. Scenarios do not threaten stability. The base holds firm.", weight: 3 },
      { text: "The lion is secured on all fronts. No gaps are present. Protection is absolute.", weight: 3 },
      { text: "The lion holds with overwhelming margin. No force challenges the system. It remains steady.", weight: 3 },
      { text: "The lion stands independent of conditions. Outcomes do not rely on timing. Stability is constant.", weight: 3 },
      { text: "The lion rests in surplus. Excess remains after all demands. The base is untouched.", weight: 3 },
      { text: "The lion holds without effort. The system sustains itself. No intervention is needed.", weight: 3 },
      { text: "The lion stands far above threshold. Requirements are easily met. Buffer is abundant.", weight: 3 },
      { text: "The lion remains in control at all times. No pressure enters. The structure absorbs all load.", weight: 3 },
      { text: "The lion operates beyond demand. Capacity is never tested. Strength is consistent.", weight: 3 },
      { text: "The lion stands protected on all sides. No weakness is exposed. Stability is certain.", weight: 3 },
      { text: "The lion holds in quiet excess. Everything is covered. Nothing is at risk.", weight: 3 },
    ],
    guidance: [
      { text: "Income is fully supported by returns. Capital remains untouched. Surplus is clearly present.", weight: 3 },
      { text: "The structure exceeds requirements. Current strategy can be maintained. No adjustment is required.", weight: 3 },
      { text: "Strong buffer is available across scenarios. Downside conditions do not impact the base. Stability holds.", weight: 3 },
      { text: "Returns comfortably exceed withdrawals. Excess is retained. Pressure does not reach the system.", weight: 3 },
      { text: "No dependency on favourable conditions. Outcomes remain consistent. The structure is reliable.", weight: 3 },
      { text: "Capital preservation is intact under stress. The base remains whole. Risk of depletion is minimal.", weight: 3 },
      { text: "System operates above demand. Capacity is underutilised. Efficiency can be improved if desired.", weight: 3 },
      { text: "Flexibility is available without weakening stability. Adjustments can be made safely. The base remains protected.", weight: 3 },
      { text: "Performance remains strong across conservative assumptions. Variability is absorbed. No strain appears.", weight: 3 },
      { text: "No corrective action is needed. Maintain current course. Optimisation is optional.", weight: 3 },
      { text: "Buffer levels exceed typical requirements. Protection against volatility is strong. The system holds.", weight: 3 },
      { text: "Income draw remains well within sustainable limits. Returns provide clear coverage. Stability is consistent.", weight: 3 },
      { text: "Structure performs beyond required thresholds. Outcomes are secure. No monitoring pressure is required.", weight: 3 },
      { text: "Downside scenarios are already covered. Timing differences do not affect sustainability. The base holds.", weight: 3 },
      { text: "System strength allows room for flexibility. Decisions can be made without risk to stability.", weight: 3 },
      { text: "Surplus returns provide meaningful protection. Volatility does not impact outcomes materially.", weight: 3 },
      { text: "No structural strain is observed. The system carries itself. Discipline is maintained.", weight: 3 },
      { text: "Current trajectory remains strong. No intervention is necessary. Stability is fully intact.", weight: 3 },
      { text: "All key variables remain within safe range. Performance is consistent. The base is preserved.", weight: 3 },
      { text: "Focus can shift from protection to optimisation. The system is already secure.", weight: 3 },
    ],
  },
  STABLE: {
    headlines: [
      { text: "The lion stands, but margin is limited. Pressure is contained. There is little room to stretch.", weight: 3 },
      { text: "The lion holds, but cannot afford disruption. The system works. Conditions must remain steady.", weight: 3 },
      { text: "The lion stands, but must remain consistent. Balance is maintained. Variability will be felt.", weight: 3 },
      { text: "The lion holds, but relies on stability. The base is intact. Outcomes depend on conditions holding.", weight: 3 },
      { text: "The lion stands, but leaves little unused. Capacity is sufficient. Surplus is minimal.", weight: 3 },
      { text: "The lion holds, but does not operate in excess. Requirements are met. Nothing extra remains.", weight: 3 },
      { text: "The lion stands, but cannot absorb shocks easily. Structure is sound. Buffer is not deep.", weight: 3 },
      { text: "The lion holds, but margin can compress. Pressure is manageable. Volatility may tighten outcomes.", weight: 3 },
      { text: "The lion stands, but must stay disciplined. Balance is present. Deviation may impact stability.", weight: 3 },
      { text: "The lion holds, but relies on current conditions. The system performs. Changes will matter.", weight: 3 },
      { text: "The lion stands, but cannot extend further. Capacity is near limit. No extra room is available.", weight: 3 },
      { text: "The lion holds, but pressure is present. Structure is intact. The system must remain controlled.", weight: 3 },
      { text: "The lion stands, but stability is not surplus. Balance holds. Protection is not deep.", weight: 3 },
      { text: "The lion holds, but depends on steady returns. Income is supported. Cushion is limited.", weight: 3 },
      { text: "The lion stands, but cannot ignore changes. Conditions matter. Stability must be maintained.", weight: 3 },
      { text: "The lion holds, but remains within limits. Structure performs. There is no excess capacity.", weight: 3 },
      { text: "The lion stands, but must be monitored. Balance is stable. Movement may affect outcomes.", weight: 3 },
      { text: "The lion holds, but timing matters. The system works. Variations will be felt.", weight: 3 },
      { text: "The lion stands, but cannot relax fully. Stability is present. Pressure is not far.", weight: 3 },
      { text: "The lion holds, but operates tightly. Requirements are met. Margin remains thin.", weight: 3 },
    ],
    guidance: [
      { text: "Income is supported by returns, but buffer is limited. Capital is intact. Surplus is not significant.", weight: 3 },
      { text: "The structure holds under expected conditions. Downside scenarios may create pressure. Monitoring is required.", weight: 3 },
      { text: "Returns broadly match withdrawals. Cushion is present but not deep. Stability depends on consistency.", weight: 3 },
      { text: "The plan remains workable, but the margin is not wide. Small changes could affect the outcome, so strengthening the structure is advisable.", weight: 3 },
      { text: "Moderate buffer exists, but can compress under stress. Volatility may affect sustainability.", weight: 3 },
      { text: "Stability is present, but not excess. The system performs within limits. Improvement is recommended.", weight: 3 },
      { text: "Current trajectory holds, but relies on conditions remaining stable. Deviations may affect balance.", weight: 3 },
      { text: "Minor inefficiencies may weaken durability over time. Addressing them will strengthen outcomes.", weight: 3 },
      { text: "Risk is controlled, but not fully insulated. External factors will have impact.", weight: 3 },
      { text: "Buffer provides some protection, but not across all scenarios. Additional margin is beneficial.", weight: 3 },
      { text: "Sustainability is intact, but not deeply protected. Monitoring and adjustment remain important.", weight: 3 },
      { text: "Structure performs well under base assumptions. Stress conditions may create strain.", weight: 3 },
      { text: "Small optimisation in returns or contributions will improve resilience. This strengthens the system.", weight: 3 },
      { text: "Plan remains on track, but margin for error is limited. Discipline is required.", weight: 3 },
      { text: "Returns support income, but leave little excess. Building buffer is recommended.", weight: 3 },
      { text: "Stability depends on maintaining current behaviour. Changes may affect outcomes.", weight: 3 },
      { text: "Downside scenarios are manageable, but not fully covered. Additional protection is advisable.", weight: 3 },
      { text: "Reinforcement is optional, but beneficial. It improves durability and reduces pressure.", weight: 3 },
      { text: "Current setup works, but does not provide strong protection. Strengthening is recommended.", weight: 3 },
      { text: "Incremental improvements will enhance stability. The system benefits from added margin.", weight: 3 },
    ],
  },
  FRAGILE: {
    headlines: [
      { text: "The lion pauses. The balance is delicate. Pressure is building beneath.", weight: 3 },
      { text: "The lion treads carefully. Margins are thin. Movement must be controlled.", weight: 3 },
      { text: "The lion watches closely. Stability is not assured. Risk is emerging.", weight: 3 },
      { text: "The lion holds for now. Conditions must hold. Pressure is rising.", weight: 3 },
      { text: "The lion tests the ground. Support is uneven. Balance may shift.", weight: 3 },
      { text: "The lion hesitates. The base feels uncertain. Stability is not firm.", weight: 3 },
      { text: "The lion stands cautiously. Balance is fragile. Small changes will matter.", weight: 3 },
      { text: "The lion moves slowly. Conditions are tightening. Pressure is increasing.", weight: 3 },
      { text: "The lion measures each step. Stability is conditional. Outcomes are sensitive.", weight: 3 },
      { text: "The lion scans the horizon. Risk is visible. Stability is not guaranteed.", weight: 3 },
      { text: "The lion shifts weight. Balance is not fixed. Conditions may change.", weight: 3 },
      { text: "The lion stands alert. Pressure is building. The system is exposed.", weight: 3 },
      { text: "The lion steadies briefly. Support is limited. Stability may not hold.", weight: 3 },
      { text: "The lion adjusts stance. Balance fluctuates. Conditions are unstable.", weight: 3 },
      { text: "The lion holds lightly. Ground feels uncertain. Pressure is present.", weight: 3 },
      { text: "The lion moves with care. Risk is active. Stability depends on control.", weight: 3 },
      { text: "The lion stands guarded. Conditions are sensitive. Movement matters.", weight: 3 },
      { text: "The lion pauses mid-step. Balance is exposed. Pressure is near.", weight: 3 },
      { text: "The lion holds tension. Stability is temporary. Conditions must cooperate.", weight: 3 },
      { text: "The lion remains cautious. Structure is not firm. Risk remains present.", weight: 3 },
    ],
    guidance: [
      { text: "Income and returns are closely matched. Margin is minimal. Small changes will affect outcomes.", weight: 3 },
      { text: "Limited buffer is available. Downside scenarios may lead to shortfall. Reinforcement is recommended.", weight: 3 },
      { text: "Structure functions, but lacks resilience. Stability is conditional. Improvements are needed.", weight: 3 },
      { text: "Performance is near breakeven. Slight deterioration may cause imbalance. Monitoring is important.", weight: 3 },
      { text: "Capital preservation is uncertain under stress. The base may be affected. Risk is present.", weight: 3 },
      { text: "Adjustments are not urgent, but should not be delayed. Timing matters for recovery.", weight: 3 },
      { text: "Exposure to volatility is meaningful. Buffer may not absorb shocks fully. Strengthening is advised.", weight: 3 },
      { text: "Current trajectory is sensitive. Small inefficiencies may create gaps. Optimisation is beneficial.", weight: 3 },
      { text: "Sustainability depends on favourable conditions. Variability will impact outcomes.", weight: 3 },
      { text: "Buffer is minimal and can erode quickly. Careful management is required.", weight: 3 },
      { text: "Returns and withdrawals are tightly matched. Little flexibility is available.", weight: 3 },
      { text: "Plan is workable, but not durable. Reinforcement improves reliability.", weight: 3 },
      { text: "Gradual erosion is possible without adjustment. Stability may decline over time.", weight: 3 },
      { text: "Balance is conditional on steady performance. Deviations will affect outcomes.", weight: 3 },
      { text: "Small improvements can restore stability. Action is beneficial at this stage.", weight: 3 },
      { text: "Risk of depletion is present under stress scenarios. Buffer should be strengthened.", weight: 3 },
      { text: "Monitoring and light intervention are required. Passive approach is not sufficient.", weight: 3 },
      { text: "Structure requires reinforcement to improve durability. Adjustments will help.", weight: 3 },
      { text: "Slight underperformance may lead to shortfall. Protection is not strong.", weight: 3 },
      { text: "Target remains achievable, but requires action. Stability is not secure.", weight: 3 },
    ],
  },
  AT_RISK: {
    headlines: [
      { text: "The lion strains. The ground is unstable. Balance is weakening.", weight: 3 },
      { text: "The lion falters. Support is thinning. Pressure is rising quickly.", weight: 3 },
      { text: "The lion yields ground. The system is slipping. Stability is declining.", weight: 3 },
      { text: "The lion shows fatigue. Structure is weakening. Load is too heavy.", weight: 3 },
      { text: "The lion leans heavily. Balance is compromised. Support is insufficient.", weight: 3 },
      { text: "The lion stumbles. The base is giving way. Stability is breaking.", weight: 3 },
      { text: "The lion bends under load. Pressure exceeds capacity. Structure cannot hold.", weight: 3 },
      { text: "The lion loses footing. Stability is failing. The system is under stress.", weight: 3 },
      { text: "The lion recoils. Stress is visible. Balance is unstable.", weight: 3 },
      { text: "The lion struggles to hold. The structure is slipping. Pressure dominates.", weight: 3 },
      { text: "The lion wavers. Ground is unreliable. Stability is not holding.", weight: 3 },
      { text: "The lion dips. Pressure exceeds support. The base is weakening.", weight: 3 },
      { text: "The lion tilts. Balance is unstable. Structure is under strain.", weight: 3 },
      { text: "The lion falters mid-step. Support weakens. Control is slipping.", weight: 3 },
      { text: "The lion braces. Strain is increasing. Stability is declining.", weight: 3 },
      { text: "The lion drifts backward. Control is reducing. Pressure is rising.", weight: 3 },
      { text: "The lion holds poorly. Stability is compromised. The system is exposed.", weight: 3 },
      { text: "The lion staggers. Structure is under stress. Balance is breaking.", weight: 3 },
      { text: "The lion sinks slightly. Support is eroding. Stability is failing.", weight: 3 },
      { text: "The lion cannot steady fully. Pressure dominates. Structure is weakening.", weight: 3 },
    ],
    guidance: [
      { text: "Income exceeds sustainable levels. Capital drawdown is likely. Immediate action is required.", weight: 3 },
      { text: "Current structure is weakening over time. Stability cannot be maintained. Adjustment is necessary.", weight: 3 },
      { text: "Returns are insufficient to support withdrawals. The gap is widening. Intervention is needed.", weight: 3 },
      { text: "Buffer has been largely exhausted. Protection is minimal. Risk of depletion is rising.", weight: 3 },
      { text: "Stability cannot hold under current conditions. Structural weakness is present.", weight: 3 },
      { text: "Without adjustment, depletion becomes likely. Recovery becomes harder over time.", weight: 3 },
      { text: "Immediate optimisation is required. Reducing withdrawals or increasing contributions is necessary.", weight: 3 },
      { text: "Capital erosion is occurring. The base is being drawn down. This must be addressed.", weight: 3 },
      { text: "Risk of failure is elevated across scenarios. Stress conditions accelerate decline.", weight: 3 },
      { text: "Delay in action increases recovery difficulty. The window for correction is narrowing.", weight: 3 },
      { text: "Structure cannot sustain long-term objectives. Meaningful changes are required.", weight: 3 },
      { text: "Returns alone cannot stabilise outcomes. Rebalancing is needed.", weight: 3 },
      { text: "Pressure exceeds system capacity. The structure is under strain.", weight: 3 },
      { text: "Sustainability gap is widening. Stability is declining. Action is required.", weight: 3 },
      { text: "Intervention is necessary to prevent further erosion. The system is weakening.", weight: 3 },
      { text: "Adjustments must be deliberate and timely. Passive approach will worsen outcomes.", weight: 3 },
      { text: "Recovery remains possible, but requires action now. Delay increases risk.", weight: 3 },
      { text: "All key variables need review. Current setup is not sufficient.", weight: 3 },
      { text: "Stability is compromised. Protection is limited. Immediate response is required.", weight: 3 },
      { text: "Corrective action is required to restore balance. The system cannot continue as is.", weight: 3 },
    ],
  },
  NOT_SUSTAINABLE: {
    headlines: [
      { text: "The lion retreats. The ground has failed. Stability is gone.", weight: 3 },
      { text: "The lion is under threat. Collapse is near. The system cannot hold.", weight: 3 },
      { text: "The lion cannot hold. Structure breaks. The base has failed.", weight: 3 },
      { text: "The lion is exposed. No support remains. Stability has ended.", weight: 3 },
      { text: "The lion withdraws. Survival overrides ambition. The system fails.", weight: 3 },
      { text: "The lion falls back. The base has collapsed. Recovery is uncertain.", weight: 3 },
      { text: "The lion is overwhelmed. Stability is gone. Pressure dominates fully.", weight: 3 },
      { text: "The lion loses ground entirely. Failure is imminent. No recovery holds.", weight: 3 },
      { text: "The lion breaks formation. Structure no longer holds. Stability is lost.", weight: 3 },
      { text: "The lion abandons position. The system fails. The base collapses.", weight: 3 },
      { text: "The lion collapses. No footing remains. Stability cannot be restored.", weight: 3 },
      { text: "The lion gives way. Pressure overwhelms. The structure is broken.", weight: 3 },
      { text: "The lion cannot recover stance. Structure is lost. Stability is gone.", weight: 3 },
      { text: "The lion falls through. Support disappears. The system fails completely.", weight: 3 },
      { text: "The lion is overrun. Stability has ended. No control remains.", weight: 3 },
      { text: "The lion drops fully. Ground is gone. The base has failed.", weight: 3 },
      { text: "The lion cannot stand. Failure is complete. The system is broken.", weight: 3 },
      { text: "The lion is displaced. No structure holds. Stability is lost entirely.", weight: 3 },
      { text: "The lion yields entirely. System breakdown occurs. No recovery without change.", weight: 3 },
      { text: "The lion is defeated. Stability cannot be restored without major change.", weight: 3 },
    ],
    guidance: [
      { text: "Current plan is not viable. Immediate restructuring is required. Continuation will lead to failure.", weight: 3 },
      { text: "Capital depletion is imminent. The system cannot sustain current withdrawals. Urgent action is needed.", weight: 3 },
      { text: "Income levels are unsupportable. Returns cannot maintain structure. Immediate reduction is required.", weight: 3 },
      { text: "Existing structure has failed. Target outcomes cannot be achieved. Full adjustment is necessary.", weight: 3 },
      { text: "All key variables must be changed. Current assumptions are not workable.", weight: 3 },
      { text: "Preservation must take priority. Income objectives are no longer achievable.", weight: 3 },
      { text: "Recovery is possible but requires significant change. Minor adjustments are not sufficient.", weight: 3 },
      { text: "Delay will worsen outcomes. Available recovery options will reduce quickly.", weight: 3 },
      { text: "Immediate corrective action is non-optional. The system cannot continue as is.", weight: 3 },
      { text: "Failure risk is near certain under current path. Intervention is critical.", weight: 3 },
      { text: "Capital exhaustion is already in motion. Stability has broken down.", weight: 3 },
      { text: "Withdrawal levels must be reduced significantly. Current levels are not viable.", weight: 3 },
      { text: "Returns are insufficient to support structure. Rebuilding is required.", weight: 3 },
      { text: "Significant capital injection may be needed. The base is no longer sufficient.", weight: 3 },
      { text: "Timeline assumptions must be extended. Current expectations are not realistic.", weight: 3 },
      { text: "The system requires full reset. Partial fixes will not restore stability.", weight: 3 },
      { text: "Continuation without change guarantees failure. Action must be immediate.", weight: 3 },
      { text: "Structural breakdown has occurred. Recovery requires decisive steps.", weight: 3 },
      { text: "Risk of full depletion is extremely high. Protection is no longer present.", weight: 3 },
      { text: "Only substantial changes can restore viability. The current path is not sustainable.", weight: 3 },
    ],
  },
};
