export type Tier = 'STRONG' | 'STABLE' | 'FRAGILE' | 'AT_RISK' | 'NOT_SUSTAINABLE';

export type Line = {
  text: string;
  weight: number;
};

export const LION_COPY: Record<
  Tier,
  {
    headlines: Line[];
    guidance: Line[];
  }
> = {
  STRONG: {
    headlines: [
      { text: '•\tThe lion is unshaken. The structure endures. ', weight: 3 },
      { text: '•\tThe lion is at ease. Strength is embedded. ', weight: 3 },
      { text: '•\tThe lion holds ground. Nothing is drawn from the core. ', weight: 3 },
      { text: '•\tThe lion is composed. Income flows without strain. ', weight: 3 },
      { text: '•\tThe lion rests in strength. The base remains untouched. ', weight: 3 },
      { text: '•\tThe lion is still. Surplus surrounds the core. ', weight: 3 },
      { text: '•\tThe lion stands unchallenged. The system holds effortlessly. ', weight: 3 },
      { text: '•\tThe lion is settled. Stability is unquestioned. ', weight: 3 },
      { text: '•\tThe lion anchors firmly. Excess capacity is present. ', weight: 3 },
      { text: '•\tThe lion remains untouched. The structure outperforms demand. ', weight: 3 },
      { text: '•\tThe lion is grounded. The foundation is secure. ', weight: 3 },
      { text: '•\tThe lion stands calm. No pressure reaches the core. ', weight: 3 },
      { text: '•\tThe lion holds steady. Strength exceeds need. ', weight: 3 },
      { text: '•\tThe lion rests easy. The system carries itself. ', weight: 3 },
      { text: '•\tThe lion is firm. The base is preserved. ', weight: 3 },
      { text: '•\tThe lion stands tall. The structure is overbuilt. ', weight: 3 },
      { text: '•\tThe lion is anchored deep. Stability is absolute. ', weight: 3 },
      { text: '•\tThe lion remains composed. No strain is visible. ', weight: 3 },
      { text: '•\tThe lion is untroubled. The system absorbs all load. ', weight: 3 },
      { text: '•\tThe lion sits in strength. Capacity exceeds demand. ', weight: 3 },
    ],
    guidance: [
      { text: '•\tIncome is fully supported by returns. Principal remains intact across scenarios. ', weight: 3 },
      { text: '•\tThe structure exceeds requirements. Current strategy can be maintained with confidence. ', weight: 3 },
      { text: '•\tStrong surplus capacity. No immediate optimisation required. ', weight: 3 },
      { text: '•\tCapital preservation is intact with room to absorb variability. ', weight: 3 },
      { text: '•\tSystem is robust. Focus shifts from protection to optimisation. ', weight: 3 },
      { text: '•\tReturns comfortably exceed withdrawals. Buffer is substantial. ', weight: 3 },
      { text: '•\tNo structural strain observed. Maintain course with discipline. ', weight: 3 },
      { text: '•\tDownside scenarios remain covered. Risk of depletion is minimal. ', weight: 3 },
      { text: '•\tCapacity is underutilised. Efficiency improvements may be considered. ', weight: 3 },
      { text: '•\tPortfolio strength allows flexibility without compromising stability. ', weight: 3 },
      { text: '•\tSurplus returns provide meaningful protection against volatility. ', weight: 3 },
      { text: '•\tStructure holds across conservative assumptions. ', weight: 3 },
      { text: '•\tIncome draw remains well within sustainable limits. ', weight: 3 },
      { text: '•\tNo dependency on favourable conditions to sustain outcomes. ', weight: 3 },
      { text: '•\tStability is resilient to shocks and timing differences. ', weight: 3 },
      { text: '•\tBuffer levels exceed typical requirements. ', weight: 3 },
      { text: '•\tCapital base remains intact under stress scenarios. ', weight: 3 },
      { text: '•\tSystem performance outpaces required thresholds. ', weight: 3 },
      { text: '•\tNo corrective action needed under current trajectory. ', weight: 3 },
      { text: '•\tOptimisation is optional, not necessary. ', weight: 3 },
    ],
  },
  STABLE: {
    headlines: [
      { text: '•\tThe lion stands firm. Pressure is contained. ', weight: 3 },
      { text: '•\tThe lion is steady. The balance holds. ', weight: 3 },
      { text: '•\tThe lion anchors the ground. Stability is evident. ', weight: 3 },
      { text: '•\tThe lion maintains posture. Load is manageable. ', weight: 3 },
      { text: '•\tThe lion holds position. Structure is reliable. ', weight: 3 },
      { text: '•\tThe lion is grounded. Strength is visible. ', weight: 3 },
      { text: '•\tThe lion stands composed. Tension is controlled. ', weight: 3 },
      { text: '•\tThe lion holds steady. Movement is measured. ', weight: 3 },
      { text: '•\tThe lion remains upright. Support is sufficient. ', weight: 3 },
      { text: '•\tThe lion steadies the field. Balance is maintained. ', weight: 3 },
      { text: '•\tThe lion stands anchored. Pressure is absorbed. ', weight: 3 },
      { text: '•\tThe lion is firm. Stability is consistent. ', weight: 3 },
      { text: '•\tThe lion holds shape. Structure is intact. ', weight: 3 },
      { text: '•\tThe lion stands balanced. Load is sustainable. ', weight: 3 },
      { text: '•\tThe lion is stable. No immediate weakness appears. ', weight: 3 },
      { text: '•\tThe lion holds ground well. Pressure is moderate. ', weight: 3 },
      { text: '•\tThe lion stands secure. Movement is controlled. ', weight: 3 },
      { text: '•\tThe lion remains firm. Structure performs as expected. ', weight: 3 },
      { text: '•\tThe lion holds with confidence. Stability is visible. ', weight: 3 },
      { text: '•\tThe lion stands resilient. Pressure remains manageable. ', weight: 3 },
    ],
    guidance: [
      { text: '•\tSustainable with moderate buffer. Minor enhancements will improve resilience. ', weight: 3 },
      { text: '•\tCurrent plan holds under expected conditions. Build additional margin where possible. ', weight: 3 },
      { text: '•\tStability is present but not excess. Incremental improvements are advisable. ', weight: 3 },
      { text: '•\tReturns support income with limited cushion. Consider light reinforcement. ', weight: 3 },
      { text: '•\tStructure is sound, though not overcapitalised. Small adjustments add durability. ', weight: 3 },
      { text: '•\tModerate surplus exists. Strengthen buffers to withstand volatility. ', weight: 3 },
      { text: '•\tPlan is viable but sensitive to downside scenarios. ', weight: 3 },
      { text: '•\tSlight optimisation in returns or contributions will enhance stability. ', weight: 3 },
      { text: '•\tMaintain course, with periodic reinforcement to avoid erosion. ', weight: 3 },
      { text: '•\tRisk is controlled, though not fully insulated. ', weight: 3 },
      { text: '•\tBuffer exists but may compress under stress. ', weight: 3 },
      { text: '•\tStructure performs well under base assumptions. ', weight: 3 },
      { text: '•\tMinor inefficiencies can be addressed to improve durability. ', weight: 3 },
      { text: '•\tSustainability is intact but not deeply protected. ', weight: 3 },
      { text: '•\tPlan remains on track with limited margin for error. ', weight: 3 },
      { text: '•\tConservative adjustments will strengthen resilience. ', weight: 3 },
      { text: '•\tReturns broadly match withdrawal needs. ', weight: 3 },
      { text: '•\tStability depends on maintaining current conditions. ', weight: 3 },
      { text: '•\tSmall changes can meaningfully improve outcomes. ', weight: 3 },
      { text: '•\tReinforcement is optional but advisable. ', weight: 3 },
    ],
  },
  FRAGILE: {
    headlines: [
      { text: '•\tThe lion pauses. The balance is delicate. ', weight: 3 },
      { text: '•\tThe lion treads carefully. Margins are thin. ', weight: 3 },
      { text: '•\tThe lion watches closely. Stability is not assured. ', weight: 3 },
      { text: '•\tThe lion holds for now. Pressure builds beneath. ', weight: 3 },
      { text: '•\tThe lion tests the ground. Support is uneven. ', weight: 3 },
      { text: '•\tThe lion hesitates. The base feels uncertain. ', weight: 3 },
      { text: '•\tThe lion stands cautiously. Balance is fragile. ', weight: 3 },
      { text: '•\tThe lion moves slowly. Conditions are tightening. ', weight: 3 },
      { text: '•\tThe lion measures each step. Stability is conditional. ', weight: 3 },
      { text: '•\tThe lion scans the horizon. Risk is emerging. ', weight: 3 },
      { text: '•\tThe lion shifts weight. Balance is not fixed. ', weight: 3 },
      { text: '•\tThe lion stands alert. Pressure is building. ', weight: 3 },
      { text: '•\tThe lion steadies briefly. Support is limited. ', weight: 3 },
      { text: '•\tThe lion adjusts stance. Stability fluctuates. ', weight: 3 },
      { text: '•\tThe lion holds lightly. Ground feels uncertain. ', weight: 3 },
      { text: '•\tThe lion moves with care. Risk is present. ', weight: 3 },
      { text: '•\tThe lion stands guarded. Conditions are sensitive. ', weight: 3 },
      { text: '•\tThe lion pauses mid-step. Balance is exposed. ', weight: 3 },
      { text: '•\tThe lion holds tension. Stability is temporary. ', weight: 3 },
      { text: '•\tThe lion remains cautious. Structure is not firm. ', weight: 3 },
    ],
    guidance: [
      { text: '•\tNear breakeven. Small changes can shift outcome materially. ', weight: 3 },
      { text: '•\tLimited margin for error. Adjust withdrawals, returns, or timing. ', weight: 3 },
      { text: '•\tCapital preservation is uncertain under current assumptions. ', weight: 3 },
      { text: '•\tStructure functions but lacks resilience. Reinforcement is recommended. ', weight: 3 },
      { text: '•\tA narrow gap exists. Modest optimisation can restore balance. ', weight: 3 },
      { text: '•\tPerformance is borderline. Slight deterioration may cause shortfall. ', weight: 3 },
      { text: '•\tAdjustments are not urgent but should not be delayed. ', weight: 3 },
      { text: '•\tExposure to volatility is meaningful. Strengthen buffers where possible. ', weight: 3 },
      { text: '•\tCurrent trajectory requires monitoring and light intervention. ', weight: 3 },
      { text: '•\tSustainability depends on favourable conditions holding. ', weight: 3 },
      { text: '•\tBuffer is minimal. Small shocks may disrupt balance. ', weight: 3 },
      { text: '•\tReturns and withdrawals are closely matched. ', weight: 3 },
      { text: '•\tPlan is workable but not durable. ', weight: 3 },
      { text: '•\tMinor inefficiencies create potential gaps. ', weight: 3 },
      { text: '•\tStability may not persist under stress. ', weight: 3 },
      { text: '•\tGradual erosion is possible without adjustment. ', weight: 3 },
      { text: '•\tReinforcement will improve outcome reliability. ', weight: 3 },
      { text: '•\tBalance is conditional on steady performance. ', weight: 3 },
      { text: '•\tSlight underperformance may lead to depletion. ', weight: 3 },
      { text: '•\tTarget remains within reach with modest changes. ', weight: 3 },
    ],
  },
  AT_RISK: {
    headlines: [
      { text: '•\tThe lion strains. The ground is unstable. ', weight: 3 },
      { text: '•\tThe lion falters. Support is thinning. ', weight: 3 },
      { text: '•\tThe lion yields ground. Pressure is rising. ', weight: 3 },
      { text: '•\tThe lion shows fatigue. Structure is weakening. ', weight: 3 },
      { text: '•\tThe lion leans heavily. Balance is compromised. ', weight: 3 },
      { text: '•\tThe lion stumbles. The base is giving way. ', weight: 3 },
      { text: '•\tThe lion bends under load. Support is insufficient. ', weight: 3 },
      { text: '•\tThe lion loses footing. Stability is breaking. ', weight: 3 },
      { text: '•\tThe lion recoils. Stress is evident. ', weight: 3 },
      { text: '•\tThe lion struggles to hold. The structure slips. ', weight: 3 },
      { text: '•\tThe lion wavers. Ground is unreliable. ', weight: 3 },
      { text: '•\tThe lion dips. Pressure exceeds support. ', weight: 3 },
      { text: '•\tThe lion tilts. Balance is unstable. ', weight: 3 },
      { text: '•\tThe lion falters mid-step. Support weakens. ', weight: 3 },
      { text: '•\tThe lion braces. Strain is increasing. ', weight: 3 },
      { text: '•\tThe lion drifts backward. Control is slipping. ', weight: 3 },
      { text: '•\tThe lion holds poorly. Stability is compromised. ', weight: 3 },
      { text: '•\tThe lion staggers. Structure is under stress. ', weight: 3 },
      { text: '•\tThe lion sinks slightly. Support is eroding. ', weight: 3 },
      { text: '•\tThe lion cannot steady fully. Pressure dominates. ', weight: 3 },
    ],
    guidance: [
      { text: '•\tIncome exceeds sustainable levels. Intervention is required. ', weight: 3 },
      { text: '•\tCapital drawdown is likely under current path. Adjust immediately. ', weight: 3 },
      { text: '•\tStructural weakness present. Increase top-ups or reduce withdrawals. ', weight: 3 },
      { text: '•\tRecovery is possible but requires deliberate changes. ', weight: 3 },
      { text: '•\tWithout adjustment, depletion risk becomes material. ', weight: 3 },
      { text: '•\tCurrent plan erodes capital over time. Corrections are necessary. ', weight: 3 },
      { text: '•\tReturns alone cannot support withdrawals. Rebalancing required. ', weight: 3 },
      { text: '•\tBuffer has been exhausted. Reinforcement is urgent. ', weight: 3 },
      { text: '•\tStability cannot be maintained without meaningful change. ', weight: 3 },
      { text: '•\tRisk of failure is elevated under most scenarios. ', weight: 3 },
      { text: '•\tCapital depletion accelerates under stress conditions. ', weight: 3 },
      { text: '•\tImmediate optimisation required to stabilise outcomes. ', weight: 3 },
      { text: '•\tWithdrawal levels must be reconsidered. ', weight: 3 },
      { text: '•\tContributions or returns must increase meaningfully. ', weight: 3 },
      { text: '•\tCurrent structure cannot sustain long-term objectives. ', weight: 3 },
      { text: '•\tDelay in action increases recovery difficulty. ', weight: 3 },
      { text: '•\tPressure exceeds system capacity. ', weight: 3 },
      { text: '•\tSustainability gap is widening. ', weight: 3 },
      { text: '•\tIntervention window remains open but narrowing. ', weight: 3 },
      { text: '•\tMaterial adjustments required to restore balance. ', weight: 3 },
    ],
  },
  NOT_SUSTAINABLE: {
    headlines: [
      { text: '•\tThe lion retreats. The ground has failed. ', weight: 3 },
      { text: '•\tThe lion is under threat. Collapse is near. ', weight: 3 },
      { text: '•\tThe lion cannot hold. Structure breaks. ', weight: 3 },
      { text: '•\tThe lion is exposed. No support remains. ', weight: 3 },
      { text: '•\tThe lion withdraws. Survival overrides ambition. ', weight: 3 },
      { text: '•\tThe lion falls back. The base has collapsed. ', weight: 3 },
      { text: '•\tThe lion is overwhelmed. Stability is gone. ', weight: 3 },
      { text: '•\tThe lion loses ground entirely. Failure is imminent. ', weight: 3 },
      { text: '•\tThe lion breaks formation. Structure no longer holds. ', weight: 3 },
      { text: '•\tThe lion abandons position. The system fails. ', weight: 3 },
      { text: '•\tThe lion collapses. No footing remains. ', weight: 3 },
      { text: '•\tThe lion gives way. Pressure overwhelms. ', weight: 3 },
      { text: '•\tThe lion cannot recover stance. Structure is lost. ', weight: 3 },
      { text: '•\tThe lion falls through. Support disappears. ', weight: 3 },
      { text: '•\tThe lion is overrun. Stability has ended. ', weight: 3 },
      { text: '•\tThe lion drops fully. Ground is gone. ', weight: 3 },
      { text: '•\tThe lion cannot stand. Failure is complete. ', weight: 3 },
      { text: '•\tThe lion is displaced. No structure holds. ', weight: 3 },
      { text: '•\tThe lion yields entirely. System breakdown occurs. ', weight: 3 },
      { text: '•\tThe lion is defeated. Stability cannot be restored without change. ', weight: 3 },
    ],
    guidance: [
      { text: '•\tCurrent plan is untenable. Immediate restructuring required. ', weight: 3 },
      { text: '•\tRapid depletion expected without decisive action. ', weight: 3 },
      { text: '•\tSubstantial reduction in withdrawals is necessary. ', weight: 3 },
      { text: '•\tCapital and return assumptions must be materially revised. ', weight: 3 },
      { text: '•\tPriority shifts to preservation. Recovery requires significant change. ', weight: 3 },
      { text: '•\tExisting structure cannot sustain target outcomes. ', weight: 3 },
      { text: '•\tImmediate intervention required to prevent total depletion. ', weight: 3 },
      { text: '•\tAll key variables must be adjusted meaningfully. ', weight: 3 },
      { text: '•\tContinuation without change leads to failure with high certainty. ', weight: 3 },
      { text: '•\tRecovery path exists but requires aggressive correction. ', weight: 3 },
      { text: '•\tCapital exhaustion is imminent under current trajectory. ', weight: 3 },
      { text: '•\tWithdrawal levels are unsupportable. ', weight: 3 },
      { text: '•\tReturns are insufficient to maintain structure. ', weight: 3 },
      { text: '•\tSignificant capital injection may be required. ', weight: 3 },
      { text: '•\tTimeline assumptions must be extended materially. ', weight: 3 },
      { text: '•\tPreservation overrides income objectives. ', weight: 3 },
      { text: '•\tImmediate corrective action is non-optional. ', weight: 3 },
      { text: '•\tStructural failure is already in motion. ', weight: 3 },
      { text: '•\tRisk of full depletion is near certain. ', weight: 3 },
      { text: '•\tOnly substantial changes can restore viability. ', weight: 3 },
    ],
  },
};
